### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by filipekiss** [filipekiss/dotfiles#1]
- [x] Better Installation Script
 - [X] Remove Prezto
 - [x] Install ZIM
 - [x] Use Zplug to handle zsh plugins
 - [x] Try to guess what should be installed. See github.com/cowboy/dotfiles
 - [x] Separate ENV configs from user configs.
 - [x] Remove Makefile
 - [x] Add README
 - [x] Better Brewfile (maybe mix brewfile and custom script?)
 - [x] Create useful and reusable installation scripts for ubuntu

**Comment by filipekiss** [comment]
Ubuntu installation script taken basically as is from here, just a few changes: [github.com/cowboy/dotfiles/blob/master/init/20_ubuntu_apt.sh](github.com/cowboy/dotfiles/blob/master/init/20_ubuntu_apt.sh)
